CREATE TABLE IF NOT EXISTS "movies" (
    "id" SERIAL PRIMARY KEY,
    "title" VARCHAR(255) UNIQUE NOT NULL,
    "director" VARCHAR(255) NOT NULL,
    "plot" VARCHAR(255) NOT NULL,
    "created_at" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);